# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='polls/static/image')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Movies')),
            ],
        ),
    ]
