# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='movie',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
