# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170426_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
    ]
