# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_movies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
