# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20170426_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='movies',
            name='Total_Number_of_Stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='Total_Number_of_Votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
