# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170426_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, upload_to='Movie_Img'),
        ),
    ]
