# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170427_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(blank=True, upload_to='MovieImg'),
        ),
    ]
